services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "FastLead_Pass123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  fastlead:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=FastLead;User Id=sa;Password=FastLead_Pass123;TrustServerCertificate=True;MultipleActiveResultSets=true"